### ISSUE TITLE
Keyword-based search considering token delimiters in class names

### ISSUE THREAD

**Issue by svatek** [nvbach91/orecap#1]
Currently the search is carried out across natural token delimiters such as the camel case. For example, for the keyword "auto", even a class called MusicArtist is returned. A search option should ideally allow to decide whether a certain keyword should be considered for the class name as a whole or just at the token level. This would however require the tool to maintain the non-decapitalized version of the terms along with the capitalized one, and consult it to refine the set of matching items if the user chose the 'token-level' rather than the 'entity-name-level' search.

**Comment by nvbach91** [comment]
Fixed in https://github.com/nvbach91/orecap/commit/88be8b4569240dbeb214b88e4f5205acb481c85b
